TRAINER:
  XDED:
    KD_TEMP: 4.0
    REPLACE: False
    WARMUP: 0
    LAMBDA: 5.0

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

OPTIM:
  NAME: 'sgd'
  LR: 0.001
  MAX_EPOCH: 100
  LR_SCHEDULER: 'cosine'
